version: '3.8'

services:

  graphqlnode:
    build: 
      context: .
    image: mikaelmicheline/graphqlnode
    container_name: graphqlnode
    volumes:
      - ./:/usr/src/app
    tty: true
    ports:
      - "3900:3900"